services:
  - type: web
    name: reflexbookingapp
    env: python
    buildCommand: ""
    startCommand: uvicorn main:app --host=0.0.0.0 --port=10000
    envVars:
      - key: PORT
        value: 10000
